export const layoutEnum = {
    LINE: 'line',
    CIRCLE: "circle",
    SQUARE: "square",
    PERIMETER_GRID: "perimeter-grid",
    FLEX_WRAP: "flex-wrap",
    SPIRAL: "spiral",
    WAVE: "wave",
    MASONRY: "masonry",
    PHYLLOTAXIS: "phyllotaxis",
    PATH: "path",
    PERSPECTIVE: "perspective",
    ISOMETRIC: "isometric",
    TREEMAP: "treemap",
    BUBBLE: "bubble",
    VORONOI: "voronoi",
    WORD_CLOUD: "word-cloud",
    CIRCLE_PACK: "circle-pack",
    CARD_HAND: "card-hand",
    STACK: "stack",
    PAYOUT_ZONES: "payout-zones",
    SPREAD_EXPLOSION: "spread-explosion",
    PYRAMID: "pyramid",
    ORBIT: "orbit",
    DNA: "dna",
    REEL_SPINNER: "REEL_SPINNER",
} as const;